name: Create Recurring Tasks
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  recurring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 22
      - run: npm install
        working-directory: recurring-tasks
      - run: node recurring-tasks.js
        working-directory: recurring-tasks
        env:
          NOTION_TOKEN: ${{ secrets.TASKS_NOTION_TOKEN }}
          TASKS_DB_ID: ${{ secrets.TASKS_DB_ID }}
